-- AlterTable
ALTER TABLE "Unit" ADD COLUMN     "alertMaxF" DOUBLE PRECISION,
ADD COLUMN     "alertMinF" DOUBLE PRECISION,
ADD COLUMN     "probeMaxF" DOUBLE PRECISION,
ADD COLUMN     "probeMinF" DOUBLE PRECISION;
